In [3]:
#Title: 100 Column & 2 Transitions
#Author: Emily Evenden
#May 18, 2020

###Part 1: Import necessary libraries. 
#The numpy library creates arrays. The PIL library converts arrays in to PNG images. The OS library allows the user to set their working directory.
#You may need to install these libraries using conda install or pip install to run this script.
#This script will output files as .PNG. To open these in TerrSet, you will need to use the GDAL Conversion tool and transform them to .RST.

import numpy as np
from PIL import Image
import os

In [4]:
#Set Working Directory to Folder of Choice. Make sure to double the backslashes.
dir = os.chdir("C:\\Users\\Emily\\Documents\\Masters_Research\\Proposal\\Data\\100_Col_Data")

In [5]:
###Part 2: Generate Base Array of Ones to build other Files. The dimensions of this array is 100 rows by 110 columns. 
#It is integer data type. It is ordered as 'C' or contiguous. 
#For this project, the value "1" represents the category "non-Agriculture."

#Creates an empty array with the dimension requested
a = np.empty((100,100), int, 'C')
#Fills every position within the array with "1"
np.copyto(a, 1, casting='unsafe')
#Check point to make sure it worked
print (a)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [25]:
#Output the adjusted array as a separate .png file
im = Image.fromarray(a)
#Change file name here
im.save("2Tran_100_T1.png")

In [26]:
###Part 3: Created Categorical Variable of Soil Type
#This first section creates an array to represent different Soil Types.
#Soil types will act as the categorical independent variable entered into the MLP neural network.

#This section uses the array created above. This means the first 10 rows are already assigned to the value "1", aka Soil 1.

#The next 20 rows are assigned to the value "2", aka Soil 2
a[10:30,:]= 2
#The next 30 rows are assigned to the value "3", aka Soil 3
a[30:60,:]= 3
#The next 40 rows are assigned to the value "4", aka Soil 4
a[60:100,:]= 4
print (a)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [4 4 4 ... 4 4 4]
 [4 4 4 ... 4 4 4]
 [4 4 4 ... 4 4 4]]


In [27]:
#Output the adjusted "Soil Type" array as a .png file. You will find this in the working folder you assigned above.
im = Image.fromarray(a)
#Change the image name here
im.save("100_Column_Soil_Type.png")

In [7]:
###Multi-transition data
#Time 2: Half Monotonic
#This resets the array we created so every position is 1. 
a[:,:]=1

#Set the first 10 columns to 2, aka "Agriculture".
a[0:5, 0:70]=2
a[5:10, 0:70] =3

a[10:20, 0:60]=2
a[20:30, 0:60]=3

a[30:45, 0:50]=2
a[45:60, 0:50]=3

a[60:80, 0:40]=2
a[80:100, 0:40]=3
#Check point
print (a)

[[2 2 2 ... 1 1 1]
 [2 2 2 ... 1 1 1]
 [2 2 2 ... 1 1 1]
 ...
 [3 3 3 ... 1 1 1]
 [3 3 3 ... 1 1 1]
 [3 3 3 ... 1 1 1]]


In [8]:
#Output the adjusted array as a separate .png file
im = Image.fromarray(a)
#Change file name here
im.save("2Tran_100Col_T2_Half_Monotonic.png")

In [9]:
###Multi-transition data
#Time 2: Quarter Monotonic
#This resets the array we created so every position is 1. 
a[:,:]=1

a[0:5, 0:35]=2
a[5:10, 0:35] =3

a[10:20, 0:30]=2
a[20:30, 0:30]=3

a[30:45, 0:25]=2
a[45:60, 0:25]=3

a[60:80, 0:20]=2
a[80:100, 0:20]=3
#Check point
print (a)

[[2 2 2 ... 1 1 1]
 [2 2 2 ... 1 1 1]
 [2 2 2 ... 1 1 1]
 ...
 [3 3 3 ... 1 1 1]
 [3 3 3 ... 1 1 1]
 [3 3 3 ... 1 1 1]]


In [10]:
#Output the adjusted array as a separate .png file
im = Image.fromarray(a)
#Change file name here
im.save("2Tran_100Col_T2_Quarter_Monotonic.png")

In [11]:
###Multi-transition data
#Time 2: Cubic Monotonic
#This resets the array we created so every position is 1. 
a[:,:]=1

a[0:5, 0:60]=2
a[5:10, 0:60] =3

a[10:20, 0:30]=2
a[20:30, 0:30]=3

a[30:45, 0:60]=2
a[45:60, 0:60]=3

a[60:80, 0:50]=2
a[80:100, 0:50]=3
#Check point
print (a)

[[2 2 2 ... 1 1 1]
 [2 2 2 ... 1 1 1]
 [2 2 2 ... 1 1 1]
 ...
 [3 3 3 ... 1 1 1]
 [3 3 3 ... 1 1 1]
 [3 3 3 ... 1 1 1]]


In [12]:
#Output the adjusted array as a separate .png file
im = Image.fromarray(a)
#Change file name here
im.save("2Tran_100Col_Time2_Cubic.png")

In [20]:
#Eastness Layer
#This resets the array we created so every position is 1. 
a[:,:]=1

columns = a.shape[1]
print (columns)

n=0

for i in range(columns):
    n=n+1
    a[:, i]= n

print (a)

100
[[  1   2   3 ...  98  99 100]
 [  1   2   3 ...  98  99 100]
 [  1   2   3 ...  98  99 100]
 ...
 [  1   2   3 ...  98  99 100]
 [  1   2   3 ...  98  99 100]
 [  1   2   3 ...  98  99 100]]


In [21]:
#Output the adjusted array as a separate .png file
im = Image.fromarray(a)
#Change file name here
im.save("Eastness.png")

In [9]:
#Southness Layer
#This resets the array we created so every position is 1. 
a[:,:]=1

m=0
for row in a:
    m=m+1
    a[row, :]= m

print (a)

[[  1   1   1 ...   1   1   1]
 [  2   2   2 ...   2   2   2]
 [  3   3   3 ...   3   3   3]
 ...
 [ 98  98  98 ...  98  98  98]
 [ 99  99  99 ...  99  99  99]
 [100 100 100 ... 100 100 100]]


In [10]:
#Output the adjusted array as a separate .png file
im = Image.fromarray(a)
#Change file name here
im.save("Southness.png")